export const LOAD_MOVIE_SUCCESS = 'LOAD_MOVIE_SUCCESS';
export const SEARCH_MOVIE_SUCCESS = 'SEARCH_MOVIE_SUCCESS';
export const LUCKY_MOVIE_SUCCESS = 'LUCKY_MOVIE_SUCCESS';

export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const END_AJAX_CALL = 'END_AJAX_CALL';

export const CREATE_MOVIE_SUCCESS = 'CREATE_MOVIE_SUCCESS';
export const REMOVE_MOVIE_SUCCESS = 'REMOVE_MOVIE_SUCCESS';
